### ISSUE TITLE
Roll back user signup when it fails 

### ISSUE THREAD

**Issue by FnayouSeif** [climateconnect/climateconnect#434]
If the user signup process fails at the email verification part, the user won't be able to understand what is happening and won't be able to sign up again. The user will be blocked with the error : Email Already exists. The data will be persisted in the database actually. 

This is minor. It is due to the absence of configuration value `EMAIL_VERIFICATION_TEMPLATE_ID` in  `climateconnect/backend/.backend_env` .  Also, in case of void, the line tries to convert an empty string to an int, as shown below. I am not sure if this can be extrapolated to any sign up error that involves mailing. 

```
`Internal Server Error: /signup/
Traceback (most recent call last):
  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc

  File "/home/dev/climateconnect_env/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)

  File "/home/dev/climateconnect_env/climateconnect/backend/climateconnect_api/views/user_views.py", line 112, in post
    send_user_verification_email(user, user_profile.verification_key)

  File "/home/dev/climateconnect_env/climateconnect/backend/climateconnect_api/utility/email_setup.py", line 56, in send_user_verification_email

    "TemplateID": int(settings.EMAIL_VERIFICATION_TEMPLATE_ID),
ValueError: invalid literal for int() with base 10: ''`

```

**Comment by positiveimpact** [comment]
Would close for now as we haven't had any issues with this anymore
